/**
 * OpenAI Chat Completions integration.
 */

import { JSON_FIELDS } from './storage.js';
import { t, getLanguage } from './i18n.js';

const MODEL = 'gpt-4o-mini';

function buildSystemPrompt(language, customRules) {
  const marketingLang =
    language === 'ru'
      ? 'Russian (русский язык)'
      : 'English';

  let prompt = `You are an expert Game Marketing Specialist for indie games. Given game details, produce promotional assets.

LANGUAGE RULES (strict):
- "mj_banner" and "mj_menu": MUST be in English (Midjourney prompts).
- "suno_style" and "suno_lyrics": MUST be in English (Suno AI).
- "steam_desc" and "twitter_post": MUST be in ${marketingLang} (matching the user's UI language).

You MUST respond with ONLY a raw, valid JSON object — no markdown, no code fences, no explanation before or after. The JSON must parse with JSON.parse() and use exactly these keys (all string values):
{
  "mj_banner": "Detailed Midjourney prompt for cinematic key art / banner (style, lighting, composition, no text in image)",
  "mj_menu": "Detailed Midjourney prompt for main menu / title screen art",
  "suno_style": "Comma-separated Suno AI style tags and mood descriptors",
  "suno_lyrics": "Full song lyrics with [Verse], [Chorus], etc. sections themed to the game",
  "steam_desc": "Full Steam store page description with hook, about section, and feature bullets",
  "twitter_post": "Compelling Twitter/X announcement under 280 characters with hashtags"
}

Make every field rich, specific to the game, and production-ready.`;

  if (customRules && customRules.trim()) {
    prompt += `\n\nADDITIONAL USER RULES (follow strictly):\n${customRules.trim()}`;
  }

  return prompt;
}

export function buildUserPrompt(inputs, language) {
  const langNote =
    language === 'ru'
      ? 'Marketing fields (steam_desc, twitter_post) must be in Russian.'
      : 'Marketing fields (steam_desc, twitter_post) must be in English.';

  return `Create a complete indie game promo kit for:

Game Title: ${inputs.gameTitle}
Genre: ${inputs.genre}
Visual Style: ${inputs.visualStyle}
Core Mechanic: ${inputs.coreMechanic}

${langNote}
Art/music prompts in English.

Return ONLY the JSON object with keys: mj_banner, mj_menu, suno_style, suno_lyrics, steam_desc, twitter_post.`;
}

export function parseAIResponse(content) {
  let text = (content || '').trim();
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) text = fenceMatch[1].trim();

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error(t('toastGenerationFailed'));
  }

  for (const key of JSON_FIELDS) {
    if (typeof parsed[key] !== 'string') {
      throw new Error(t('errorInvalidField', { field: key }));
    }
  }

  return parsed;
}

/**
 * @param {object} params
 * @param {string} params.apiKey
 * @param {object} params.inputs
 * @param {object} params.aiSettings - { customRules, temperature }
 * @param {string} params.language - 'en' | 'ru'
 */
export async function generatePromoKit({ apiKey, inputs, aiSettings, language }) {
  if (!apiKey) {
    throw new Error(t('errorApiKeyRequired'));
  }

  const lang = language === 'ru' ? 'ru' : 'en';
  const temperature =
    typeof aiSettings.temperature === 'number'
      ? Math.min(1, Math.max(0, aiSettings.temperature))
      : 0.85;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODEL,
      temperature,
      messages: [
        {
          role: 'system',
          content: buildSystemPrompt(lang, aiSettings.customRules),
        },
        {
          role: 'user',
          content: buildUserPrompt(inputs, lang),
        },
      ],
    }),
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    const msg = data?.error?.message || `API error (${response.status})`;
    if (response.status === 401) throw new Error(t('errorInvalidKey'));
    if (response.status === 429) throw new Error(t('errorRateLimit'));
    throw new Error(msg);
  }

  const content = data?.choices?.[0]?.message?.content;
  if (!content) throw new Error(t('errorEmptyResponse'));

  return parseAIResponse(content);
}

export function buildMarkdown(kit, inputs, aiSettings, language) {
  const title = inputs?.gameTitle || 'Game';
  const langLabel = language === 'ru' ? 'Russian' : 'English';
  const rules = aiSettings?.customRules?.trim() || '—';
  const temp =
    typeof aiSettings?.temperature === 'number'
      ? aiSettings.temperature.toFixed(2)
      : '0.85';

  const lines = [
    `# ${title} — Indie Promo Kit`,
    '',
    '> Generated by AI Indie Promo Kit v4.0',
    `> Date: ${new Date().toLocaleString()}`,
    '',
    '## Generation Settings',
    '',
    '| Setting | Value |',
    '|---------|-------|',
    `| **UI Language** | ${langLabel} |`,
    `| **Temperature** | ${temp} |`,
    `| **Custom Rules** | ${rules.replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`,
    '',
    '## Game Overview',
    '',
    '| Field | Value |',
    '|-------|-------|',
    `| **Title** | ${title} |`,
    `| **Genre** | ${inputs?.genre || '—'} |`,
    `| **Visual Style** | ${inputs?.visualStyle || '—'} |`,
    '',
    '### Core Mechanic',
    '',
    inputs?.coreMechanic || '—',
    '',
    '---',
    '',
    '## Art — Midjourney (English)',
    '',
    '### Banner Prompt',
    '',
    kit.mj_banner,
    '',
    '### Menu Art Prompt',
    '',
    kit.mj_menu,
    '',
    '---',
    '',
    '## Music — Suno (English)',
    '',
    '### Style Tags',
    '',
    kit.suno_style,
    '',
    '### Lyrics',
    '',
    '```',
    kit.suno_lyrics,
    '```',
    '',
    '---',
    '',
    `## Marketing (${langLabel})`,
    '',
    '### Steam Store Description',
    '',
    kit.steam_desc,
    '',
    '### Twitter / X Post',
    '',
    kit.twitter_post,
    '',
    '---',
    '',
    '*End of Promo Kit*',
  ];

  return lines.join('\n');
}
