/**
 * Internationalization — extensible multi-language UI (EN, RU, UK, ES, DE, FR).
 */

import { getStoredLanguage, setStoredLanguage } from './storage.js';

export const LANGUAGES = [
  { code: 'en', label: 'English', locale: 'en-US' },
  { code: 'ru', label: 'Русский', locale: 'ru-RU' },
  { code: 'uk', label: 'Українська', locale: 'uk-UA' },
  { code: 'es', label: 'Español', locale: 'es-ES' },
  { code: 'de', label: 'Deutsch', locale: 'de-DE' },
  { code: 'fr', label: 'Français', locale: 'fr-FR' },
];

/** Language used for Steam / social copy in OpenAI prompts */
export const MARKETING_LANG_NAMES = {
  en: 'English',
  ru: 'Russian (русский язык)',
  uk: 'Ukrainian (українська мова)',
  es: 'Spanish (español)',
  de: 'German (Deutsch)',
  fr: 'French (français)',
};

const en = {
  appTitle: 'AI Indie Promo Kit',
  toggleHistory: 'Toggle History',
  closeSidebar: 'Close sidebar',
  apiKeyPlaceholder: 'OpenAI API Key',
  apiKeySave: 'Save',
  apiKeyEdit: 'Edit',
  apiKeyHelpTitle: 'How to get an API key',
  apiKeyHelpWhere: 'Create an API key in your OpenAI dashboard:',
  apiKeyHelpPrivacy:
    'The key is stored only in your browser’s localStorage and is sent exclusively to the official OpenAI API. It is never shared with third-party servers.',
  language: 'Language',
  aiSettings: 'AI Settings',
  projectHistory: 'Project History',
  historyEmpty: 'No kits generated yet. Create your first promo kit!',
  historyFilterAll: 'All',
  historyFilterFavorites: 'Favorites',
  addFavorite: 'Add to favorites',
  removeFavorite: 'Remove from favorites',
  deleteHistory: 'Delete',
  defineGame: 'Define Your Game',
  labelGameTitle: 'Game Title',
  placeholderGameTitle: 'e.g. Neon Drift Protocol',
  labelGenre: 'Genre',
  placeholderGenre: 'e.g. Roguelike Racing',
  labelVisualStyle: 'Visual Style',
  stylePixelArt: 'Pixel Art',
  styleUnreal: 'Unreal Engine 5',
  styleAnime: 'Anime',
  styleDarkFantasy: 'Dark Fantasy',
  styleLowPoly: 'Low Poly',
  labelCoreMechanic: 'Core Mechanic',
  placeholderCoreMechanic:
    'Describe the core gameplay loop, unique hooks, and player fantasy...',
  generateKit: 'Generate Kit',
  generating: 'Generating...',
  synthesizing: 'Synthesizing...',
  generatedKit: 'Generated Promo Kit',
  exportMarkdown: 'Export to Markdown',
  outputPlaceholderTitle: 'Your generated promo kit will appear here.',
  outputPlaceholderHint: 'Fill in the form and hit Generate Kit.',
  sectionArt: 'Art — Midjourney',
  sectionMusic: 'Music — Suno',
  sectionMarketing: 'Marketing — Steam & Social',
  labelBanner: 'Banner',
  labelMenuArt: 'Menu Art',
  labelStyle: 'Style',
  labelLyrics: 'Lyrics',
  labelSteam: 'Steam Page',
  labelTwitter: 'Twitter / X',
  copy: 'Copy',
  footer: 'AI Indie Promo Kit — Built for indie devs. API key stored locally only.',
  modalAiSettings: 'AI Settings',
  modalClose: 'Close',
  labelCustomRules: 'Custom Rules (AI Memory)',
  placeholderCustomRules:
    'e.g. Always mention our studio name. Use dark humor in social posts. Never use emoji in Steam copy.',
  labelTemperature: 'Creativity (Temperature)',
  temperatureHint: 'Lower = more focused. Higher = more creative.',
  saveSettings: 'Save Settings',
  toastDismiss: 'Dismiss',
  toastApiKeySaved: 'API key saved locally.',
  toastApiKeyInvalid: 'Please enter a valid API key.',
  toastApiKeyFormat: 'API key should typically start with "sk-".',
  toastApiKeyRequired: 'Save your OpenAI API key before generating.',
  toastFillFields: 'Please fill in all required fields.',
  toastCopied: 'Copied to clipboard.',
  toastCopyFailed: 'Failed to copy. Check browser permissions.',
  toastGenerated: 'Promo kit generated successfully!',
  toastGenerationFailed: 'Generation failed.',
  toastLoaded: 'Loaded: {title}',
  toastDeleted: 'History item deleted.',
  toastFavoriteAdded: 'Added to favorites.',
  toastFavoriteRemoved: 'Removed from favorites.',
  toastNothingExport: 'Nothing to export. Generate a kit first.',
  toastDownloaded: 'Downloaded {filename}',
  toastSettingsSaved: 'AI settings saved.',
  errorInvalidKey: 'Invalid API key. Check your key and try again.',
  errorRateLimit: 'Rate limit exceeded. Please wait and retry.',
  errorEmptyResponse: 'Empty response from API.',
  errorApiKeyRequired: 'API key is required. Save your OpenAI API key first.',
  errorInvalidField: 'Missing or invalid field: {field}',
  mdSubtitle: 'Indie Promo Kit',
  mdGeneratedBy: 'Generated by AI Indie Promo Kit',
  mdGenSettings: 'Generation Settings',
  mdSetting: 'Setting',
  mdValue: 'Value',
  mdUiLanguage: 'UI Language',
  mdTemperature: 'Temperature',
  mdCustomRules: 'Custom Rules',
  mdNone: '—',
  mdGameOverview: 'Game Overview',
  mdField: 'Field',
  mdTitle: 'Title',
  mdGenre: 'Genre',
  mdVisualStyle: 'Visual Style',
  mdCoreMechanic: 'Core Mechanic',
  mdArtEnglish: 'Art — Midjourney (English)',
  mdBannerPrompt: 'Banner Prompt',
  mdMenuPrompt: 'Menu Art Prompt',
  mdMusicEnglish: 'Music — Suno (English)',
  mdStyleTags: 'Style Tags',
  mdLyrics: 'Lyrics',
  mdMarketing: 'Marketing',
  mdSteamDesc: 'Steam Store Description',
  mdTwitterPost: 'Twitter / X Post',
  mdEnd: 'End of Promo Kit',
  apiMarketingNote:
    'Marketing fields (steam_desc, twitter_post) must be in {language}.',
};

const ru = {
  toggleHistory: 'История проектов',
  closeSidebar: 'Закрыть панель',
  apiKeyPlaceholder: 'Ключ OpenAI API',
  apiKeySave: 'Сохранить',
  apiKeyEdit: 'Изменить',
  apiKeyHelpTitle: 'Как получить ключ API',
  apiKeyHelpWhere: 'Создайте ключ API в личном кабинете OpenAI:',
  apiKeyHelpPrivacy:
    'Ключ сохраняется только в localStorage вашего браузера и передаётся исключительно на официальный API OpenAI. Мы не отправляем его на сторонние серверы.',
  language: 'Язык',
  aiSettings: 'Настройки ИИ',
  projectHistory: 'История проектов',
  historyEmpty: 'Пока нет наборов. Создайте первый промо-кит!',
  historyFilterAll: 'Все',
  historyFilterFavorites: 'Избранное',
  addFavorite: 'В избранное',
  removeFavorite: 'Убрать из избранного',
  deleteHistory: 'Удалить',
  defineGame: 'Опишите игру',
  labelGameTitle: 'Название игры',
  placeholderGameTitle: 'напр. Neon Drift Protocol',
  labelGenre: 'Жанр',
  placeholderGenre: 'напр. Roguelike-гонки',
  labelVisualStyle: 'Визуальный стиль',
  stylePixelArt: 'Пиксель-арт',
  styleDarkFantasy: 'Тёмное фэнтези',
  labelCoreMechanic: 'Основная механика',
  placeholderCoreMechanic:
    'Опишите игровой цикл, уникальные фишки и фантазию игрока...',
  generateKit: 'Сгенерировать кит',
  generating: 'Генерация...',
  synthesizing: 'Синтез...',
  generatedKit: 'Сгенерированный промо-кит',
  exportMarkdown: 'Экспорт в Markdown',
  outputPlaceholderTitle: 'Здесь появится ваш промо-кит.',
  outputPlaceholderHint: 'Заполните форму и нажмите «Сгенерировать кит».',
  sectionArt: 'Арт — Midjourney',
  sectionMusic: 'Музыка — Suno',
  sectionMarketing: 'Маркетинг — Steam и соцсети',
  labelBanner: 'Баннер',
  labelMenuArt: 'Меню',
  labelStyle: 'Стиль',
  labelLyrics: 'Текст песни',
  labelSteam: 'Страница Steam',
  copy: 'Копировать',
  footer: 'AI Indie Promo Kit — для инди-разработчиков. Ключ API хранится только локально.',
  modalAiSettings: 'Настройки ИИ',
  modalClose: 'Закрыть',
  labelCustomRules: 'Свои правила (память ИИ)',
  placeholderCustomRules:
    'напр. Всегда упоминать студию. Тёмный юмор в соцсетях. Без эмодзи в тексте Steam.',
  labelTemperature: 'Креативность (Temperature)',
  temperatureHint: 'Ниже — точнее. Выше — креативнее.',
  saveSettings: 'Сохранить настройки',
  toastDismiss: 'Закрыть',
  toastApiKeySaved: 'Ключ API сохранён локально.',
  toastApiKeyInvalid: 'Введите корректный ключ API.',
  toastApiKeyFormat: 'Ключ API обычно начинается с «sk-».',
  toastApiKeyRequired: 'Сначала сохраните ключ OpenAI API.',
  toastFillFields: 'Заполните все обязательные поля.',
  toastCopied: 'Скопировано в буфер обмена.',
  toastCopyFailed: 'Не удалось скопировать. Проверьте разрешения браузера.',
  toastGenerated: 'Промо-кит успешно сгенерирован!',
  toastGenerationFailed: 'Ошибка генерации.',
  toastLoaded: 'Загружено: {title}',
  toastDeleted: 'Запись удалена из истории.',
  toastFavoriteAdded: 'Добавлено в избранное.',
  toastFavoriteRemoved: 'Удалено из избранного.',
  toastNothingExport: 'Нечего экспортировать. Сначала сгенерируйте кит.',
  toastDownloaded: 'Скачан файл {filename}',
  toastSettingsSaved: 'Настройки ИИ сохранены.',
  errorInvalidKey: 'Неверный ключ API. Проверьте ключ и повторите.',
  errorRateLimit: 'Превышен лимит запросов. Подождите и повторите.',
  errorEmptyResponse: 'Пустой ответ от API.',
  errorApiKeyRequired: 'Нужен ключ API. Сначала сохраните ключ OpenAI.',
  errorInvalidField: 'Отсутствует или неверное поле: {field}',
  mdSubtitle: 'Инди промо-кит',
  mdGeneratedBy: 'Создано в AI Indie Promo Kit',
  mdGenSettings: 'Параметры генерации',
  mdSetting: 'Параметр',
  mdValue: 'Значение',
  mdUiLanguage: 'Язык интерфейса',
  mdTemperature: 'Temperature',
  mdCustomRules: 'Свои правила',
  mdGameOverview: 'Об игре',
  mdField: 'Поле',
  mdTitle: 'Название',
  mdGenre: 'Жанр',
  mdVisualStyle: 'Визуальный стиль',
  mdCoreMechanic: 'Основная механика',
  mdArtEnglish: 'Арт — Midjourney (англ.)',
  mdBannerPrompt: 'Промпт баннера',
  mdMenuPrompt: 'Промпт меню',
  mdMusicEnglish: 'Музыка — Suno (англ.)',
  mdStyleTags: 'Теги стиля',
  mdLyrics: 'Текст песни',
  mdMarketing: 'Маркетинг',
  mdSteamDesc: 'Описание Steam',
  mdTwitterPost: 'Пост Twitter / X',
  mdEnd: 'Конец промо-кита',
  apiMarketingNote:
    'Поля steam_desc и twitter_post должны быть на {language}.',
};

const uk = {
  toggleHistory: 'Історія проєктів',
  closeSidebar: 'Закрити панель',
  apiKeyPlaceholder: 'Ключ OpenAI API',
  apiKeySave: 'Зберегти',
  apiKeyEdit: 'Змінити',
  language: 'Мова',
  aiSettings: 'Налаштування ШІ',
  projectHistory: 'Історія проєктів',
  historyEmpty: 'Ще немає наборів. Створіть перший промо-кит!',
  historyFilterAll: 'Усі',
  historyFilterFavorites: 'Обране',
  addFavorite: 'До обраного',
  removeFavorite: 'Прибрати з обраного',
  deleteHistory: 'Видалити',
  defineGame: 'Опишіть гру',
  labelGameTitle: 'Назва гри',
  placeholderGameTitle: 'напр. Neon Drift Protocol',
  labelGenre: 'Жанр',
  placeholderGenre: 'напр. Roguelike-перегони',
  labelVisualStyle: 'Візуальний стиль',
  stylePixelArt: 'Піксель-арт',
  styleDarkFantasy: 'Темне фентезі',
  labelCoreMechanic: 'Основна механіка',
  placeholderCoreMechanic: 'Опишіть ігровий цикл, унікальні фішки та фантазію гравця...',
  generateKit: 'Згенерувати кит',
  generating: 'Генерація...',
  synthesizing: 'Синтез...',
  generatedKit: 'Згенерований промо-кит',
  exportMarkdown: 'Експорт у Markdown',
  outputPlaceholderTitle: 'Тут з’явиться ваш промо-кит.',
  outputPlaceholderHint: 'Заповніть форму та натисніть «Згенерувати кит».',
  sectionArt: 'Арт — Midjourney',
  sectionMusic: 'Музика — Suno',
  sectionMarketing: 'Маркетинг — Steam і соцмережі',
  labelBanner: 'Банер',
  labelMenuArt: 'Меню',
  labelStyle: 'Стиль',
  labelLyrics: 'Текст пісні',
  labelSteam: 'Сторінка Steam',
  copy: 'Копіювати',
  footer: 'AI Indie Promo Kit — для інді-розробників. Ключ API зберігається лише локально.',
  modalAiSettings: 'Налаштування ШІ',
  modalClose: 'Закрити',
  labelCustomRules: 'Власні правила (пам’ять ШІ)',
  placeholderCustomRules:
    'напр. Завжди згадувати студію. Темний гумор у соцмережах. Без емодзі в Steam.',
  labelTemperature: 'Креативність (Temperature)',
  temperatureHint: 'Нижче — точніше. Вище — креативніше.',
  saveSettings: 'Зберегти налаштування',
  toastApiKeySaved: 'Ключ API збережено локально.',
  toastApiKeyInvalid: 'Введіть коректний ключ API.',
  toastApiKeyRequired: 'Спочатку збережіть ключ OpenAI API.',
  toastFillFields: 'Заповніть усі обов’язкові поля.',
  toastCopied: 'Скопійовано в буфер обміну.',
  toastCopyFailed: 'Не вдалося скопіювати. Перевірте дозволи браузера.',
  toastGenerated: 'Промо-кит успішно згенеровано!',
  toastGenerationFailed: 'Помилка генерації.',
  toastLoaded: 'Завантажено: {title}',
  toastDeleted: 'Запис видалено з історії.',
  toastFavoriteAdded: 'Додано до обраного.',
  toastFavoriteRemoved: 'Прибрано з обраного.',
  toastNothingExport: 'Немає що експортувати. Спочатку згенеруйте кит.',
  toastDownloaded: 'Завантажено файл {filename}',
  toastSettingsSaved: 'Налаштування ШІ збережено.',
  errorInvalidKey: 'Невірний ключ API. Перевірте ключ і повторіть.',
  errorRateLimit: 'Перевищено ліміт запитів. Зачекайте і повторіть.',
  errorEmptyResponse: 'Порожня відповідь від API.',
  errorApiKeyRequired: 'Потрібен ключ API. Спочатку збережіть ключ OpenAI.',
  mdSubtitle: 'Інді промо-кит',
  mdGeneratedBy: 'Створено в AI Indie Promo Kit',
  mdGenSettings: 'Параметри генерації',
  mdSetting: 'Параметр',
  mdValue: 'Значення',
  mdUiLanguage: 'Мова інтерфейсу',
  mdGameOverview: 'Про гру',
  mdField: 'Поле',
  mdTitle: 'Назва',
  mdGenre: 'Жанр',
  mdVisualStyle: 'Візуальний стиль',
  mdCoreMechanic: 'Основна механіка',
  mdArtEnglish: 'Арт — Midjourney (англ.)',
  mdBannerPrompt: 'Промпт банера',
  mdMenuPrompt: 'Промпт меню',
  mdMusicEnglish: 'Музика — Suno (англ.)',
  mdStyleTags: 'Теги стилю',
  mdLyrics: 'Текст пісні',
  mdMarketing: 'Маркетинг',
  mdSteamDesc: 'Опис Steam',
  mdTwitterPost: 'Пост Twitter / X',
  mdEnd: 'Кінець промо-кита',
  apiMarketingNote:
    'Поля steam_desc і twitter_post мають бути {language}.',
};

const es = {
  language: 'Idioma',
  aiSettings: 'Ajustes de IA',
  projectHistory: 'Historial de proyectos',
  historyEmpty: 'Aún no hay kits. ¡Crea tu primer promo kit!',
  historyFilterAll: 'Todos',
  historyFilterFavorites: 'Favoritos',
  addFavorite: 'Añadir a favoritos',
  removeFavorite: 'Quitar de favoritos',
  deleteHistory: 'Eliminar',
  defineGame: 'Define tu juego',
  labelGameTitle: 'Título del juego',
  placeholderGameTitle: 'ej. Neon Drift Protocol',
  labelGenre: 'Género',
  placeholderGenre: 'ej. Carreras roguelike',
  labelVisualStyle: 'Estilo visual',
  labelCoreMechanic: 'Mecánica principal',
  placeholderCoreMechanic: 'Describe el bucle de juego, ganchos únicos y la fantasía del jugador...',
  generateKit: 'Generar kit',
  generating: 'Generando...',
  synthesizing: 'Sintetizando...',
  generatedKit: 'Promo kit generado',
  exportMarkdown: 'Exportar a Markdown',
  outputPlaceholderTitle: 'Tu promo kit aparecerá aquí.',
  outputPlaceholderHint: 'Completa el formulario y pulsa Generar kit.',
  sectionArt: 'Arte — Midjourney',
  sectionMusic: 'Música — Suno',
  sectionMarketing: 'Marketing — Steam y redes',
  labelBanner: 'Banner',
  labelMenuArt: 'Menú',
  labelStyle: 'Estilo',
  labelLyrics: 'Letra',
  labelSteam: 'Página de Steam',
  copy: 'Copiar',
  footer: 'AI Indie Promo Kit — Para desarrolladores indie. La clave API solo se guarda localmente.',
  modalAiSettings: 'Ajustes de IA',
  modalClose: 'Cerrar',
  labelCustomRules: 'Reglas personalizadas (memoria IA)',
  placeholderCustomRules:
    'ej. Mencionar siempre el estudio. Humor oscuro en redes. Sin emojis en Steam.',
  labelTemperature: 'Creatividad (Temperature)',
  temperatureHint: 'Más bajo = más preciso. Más alto = más creativo.',
  saveSettings: 'Guardar ajustes',
  toastApiKeySaved: 'Clave API guardada localmente.',
  toastApiKeyInvalid: 'Introduce una clave API válida.',
  toastApiKeyRequired: 'Guarda tu clave OpenAI antes de generar.',
  toastFillFields: 'Completa todos los campos obligatorios.',
  toastCopied: 'Copiado al portapapeles.',
  toastCopyFailed: 'Error al copiar. Revisa los permisos del navegador.',
  toastGenerated: '¡Promo kit generado con éxito!',
  toastGenerationFailed: 'Error en la generación.',
  toastLoaded: 'Cargado: {title}',
  toastDeleted: 'Entrada eliminada del historial.',
  toastFavoriteAdded: 'Añadido a favoritos.',
  toastFavoriteRemoved: 'Eliminado de favoritos.',
  toastNothingExport: 'Nada que exportar. Genera un kit primero.',
  toastDownloaded: 'Descargado {filename}',
  toastSettingsSaved: 'Ajustes de IA guardados.',
  errorInvalidKey: 'Clave API inválida. Compruébala e inténtalo de nuevo.',
  errorRateLimit: 'Límite de solicitudes excedido. Espera y reintenta.',
  errorEmptyResponse: 'Respuesta vacía de la API.',
  errorApiKeyRequired: 'Se requiere clave API. Guárdala primero.',
  mdSubtitle: 'Promo kit indie',
  mdGeneratedBy: 'Generado por AI Indie Promo Kit',
  mdGenSettings: 'Ajustes de generación',
  mdSetting: 'Ajuste',
  mdValue: 'Valor',
  mdUiLanguage: 'Idioma de la interfaz',
  mdGameOverview: 'Resumen del juego',
  mdField: 'Campo',
  mdTitle: 'Título',
  mdGenre: 'Género',
  mdVisualStyle: 'Estilo visual',
  mdCoreMechanic: 'Mecánica principal',
  mdArtEnglish: 'Arte — Midjourney (inglés)',
  mdBannerPrompt: 'Prompt del banner',
  mdMenuPrompt: 'Prompt del menú',
  mdMusicEnglish: 'Música — Suno (inglés)',
  mdStyleTags: 'Etiquetas de estilo',
  mdLyrics: 'Letra',
  mdMarketing: 'Marketing',
  mdSteamDesc: 'Descripción de Steam',
  mdTwitterPost: 'Publicación en Twitter / X',
  mdEnd: 'Fin del promo kit',
  apiMarketingNote:
    'Los campos steam_desc y twitter_post deben estar en {language}.',
};

const de = {
  language: 'Sprache',
  aiSettings: 'KI-Einstellungen',
  projectHistory: 'Projektverlauf',
  historyEmpty: 'Noch keine Kits. Erstelle dein erstes Promo-Kit!',
  historyFilterAll: 'Alle',
  historyFilterFavorites: 'Favoriten',
  addFavorite: 'Zu Favoriten hinzufügen',
  removeFavorite: 'Aus Favoriten entfernen',
  deleteHistory: 'Löschen',
  defineGame: 'Spiel definieren',
  labelGameTitle: 'Spieltitel',
  placeholderGameTitle: 'z.B. Neon Drift Protocol',
  labelGenre: 'Genre',
  placeholderGenre: 'z.B. Roguelike-Rennen',
  labelVisualStyle: 'Visueller Stil',
  labelCoreMechanic: 'Kernmechanik',
  placeholderCoreMechanic:
    'Beschreibe Gameplay-Loop, einzigartige Hooks und Spielerfantasie...',
  generateKit: 'Kit generieren',
  generating: 'Wird generiert...',
  synthesizing: 'Synthese...',
  generatedKit: 'Generiertes Promo-Kit',
  exportMarkdown: 'Als Markdown exportieren',
  outputPlaceholderTitle: 'Dein Promo-Kit erscheint hier.',
  outputPlaceholderHint: 'Formular ausfüllen und „Kit generieren“ klicken.',
  sectionArt: 'Art — Midjourney',
  sectionMusic: 'Musik — Suno',
  sectionMarketing: 'Marketing — Steam & Social',
  labelBanner: 'Banner',
  labelMenuArt: 'Menü',
  labelStyle: 'Stil',
  labelLyrics: 'Songtext',
  labelSteam: 'Steam-Seite',
  copy: 'Kopieren',
  footer:
    'AI Indie Promo Kit — Für Indie-Entwickler. API-Schlüssel nur lokal gespeichert.',
  modalAiSettings: 'KI-Einstellungen',
  modalClose: 'Schließen',
  labelCustomRules: 'Eigene Regeln (KI-Gedächtnis)',
  placeholderCustomRules:
    'z.B. Studio immer nennen. Dunkler Humor in Social Posts. Keine Emojis auf Steam.',
  labelTemperature: 'Kreativität (Temperature)',
  temperatureHint: 'Niedriger = fokussierter. Höher = kreativer.',
  saveSettings: 'Einstellungen speichern',
  toastApiKeySaved: 'API-Schlüssel lokal gespeichert.',
  toastApiKeyInvalid: 'Bitte gültigen API-Schlüssel eingeben.',
  toastApiKeyRequired: 'Speichere zuerst deinen OpenAI API-Schlüssel.',
  toastFillFields: 'Bitte alle Pflichtfelder ausfüllen.',
  toastCopied: 'In die Zwischenablage kopiert.',
  toastCopyFailed: 'Kopieren fehlgeschlagen. Browser-Berechtigungen prüfen.',
  toastGenerated: 'Promo-Kit erfolgreich generiert!',
  toastGenerationFailed: 'Generierung fehlgeschlagen.',
  toastLoaded: 'Geladen: {title}',
  toastDeleted: 'Eintrag aus dem Verlauf gelöscht.',
  toastFavoriteAdded: 'Zu Favoriten hinzugefügt.',
  toastFavoriteRemoved: 'Aus Favoriten entfernt.',
  toastNothingExport: 'Nichts zu exportieren. Zuerst ein Kit generieren.',
  toastDownloaded: '{filename} heruntergeladen',
  toastSettingsSaved: 'KI-Einstellungen gespeichert.',
  errorInvalidKey: 'Ungültiger API-Schlüssel. Prüfen und erneut versuchen.',
  errorRateLimit: 'Rate-Limit erreicht. Bitte warten und erneut versuchen.',
  errorEmptyResponse: 'Leere Antwort von der API.',
  errorApiKeyRequired: 'API-Schlüssel erforderlich. Zuerst speichern.',
  mdSubtitle: 'Indie-Promo-Kit',
  mdGeneratedBy: 'Erstellt mit AI Indie Promo Kit',
  mdGenSettings: 'Generierungseinstellungen',
  mdSetting: 'Einstellung',
  mdValue: 'Wert',
  mdUiLanguage: 'UI-Sprache',
  mdGameOverview: 'Spielübersicht',
  mdField: 'Feld',
  mdTitle: 'Titel',
  mdGenre: 'Genre',
  mdVisualStyle: 'Visueller Stil',
  mdCoreMechanic: 'Kernmechanik',
  mdArtEnglish: 'Art — Midjourney (Englisch)',
  mdBannerPrompt: 'Banner-Prompt',
  mdMenuPrompt: 'Menü-Prompt',
  mdMusicEnglish: 'Musik — Suno (Englisch)',
  mdStyleTags: 'Stil-Tags',
  mdLyrics: 'Songtext',
  mdMarketing: 'Marketing',
  mdSteamDesc: 'Steam-Beschreibung',
  mdTwitterPost: 'Twitter / X-Beitrag',
  mdEnd: 'Ende des Promo-Kits',
  apiMarketingNote:
    'Felder steam_desc und twitter_post müssen auf {language} sein.',
};

const fr = {
  language: 'Langue',
  aiSettings: 'Paramètres IA',
  projectHistory: 'Historique des projets',
  historyEmpty: 'Aucun kit pour l’instant. Créez votre premier promo kit !',
  historyFilterAll: 'Tous',
  historyFilterFavorites: 'Favoris',
  addFavorite: 'Ajouter aux favoris',
  removeFavorite: 'Retirer des favoris',
  deleteHistory: 'Supprimer',
  defineGame: 'Décrivez votre jeu',
  labelGameTitle: 'Titre du jeu',
  placeholderGameTitle: 'ex. Neon Drift Protocol',
  labelGenre: 'Genre',
  placeholderGenre: 'ex. Course roguelike',
  labelVisualStyle: 'Style visuel',
  labelCoreMechanic: 'Mécanique principale',
  placeholderCoreMechanic:
    'Décrivez la boucle de gameplay, les accroches uniques et la fantasy du joueur...',
  generateKit: 'Générer le kit',
  generating: 'Génération...',
  synthesizing: 'Synthèse...',
  generatedKit: 'Promo kit généré',
  exportMarkdown: 'Exporter en Markdown',
  outputPlaceholderTitle: 'Votre promo kit apparaîtra ici.',
  outputPlaceholderHint: 'Remplissez le formulaire et cliquez sur Générer le kit.',
  sectionArt: 'Art — Midjourney',
  sectionMusic: 'Musique — Suno',
  sectionMarketing: 'Marketing — Steam & réseaux',
  labelBanner: 'Bannière',
  labelMenuArt: 'Menu',
  labelStyle: 'Style',
  labelLyrics: 'Paroles',
  labelSteam: 'Page Steam',
  copy: 'Copier',
  footer:
    'AI Indie Promo Kit — Pour les devs indie. Clé API stockée localement uniquement.',
  modalAiSettings: 'Paramètres IA',
  modalClose: 'Fermer',
  labelCustomRules: 'Règles personnalisées (mémoire IA)',
  placeholderCustomRules:
    'ex. Toujours mentionner le studio. Humour noir sur les réseaux. Pas d’emoji sur Steam.',
  labelTemperature: 'Créativité (Temperature)',
  temperatureHint: 'Plus bas = plus précis. Plus haut = plus créatif.',
  saveSettings: 'Enregistrer',
  toastApiKeySaved: 'Clé API enregistrée localement.',
  toastApiKeyInvalid: 'Entrez une clé API valide.',
  toastApiKeyRequired: 'Enregistrez d’abord votre clé OpenAI.',
  toastFillFields: 'Remplissez tous les champs obligatoires.',
  toastCopied: 'Copié dans le presse-papiers.',
  toastCopyFailed: 'Échec de la copie. Vérifiez les permissions du navigateur.',
  toastGenerated: 'Promo kit généré avec succès !',
  toastGenerationFailed: 'Échec de la génération.',
  toastLoaded: 'Chargé : {title}',
  toastDeleted: 'Entrée supprimée de l’historique.',
  toastFavoriteAdded: 'Ajouté aux favoris.',
  toastFavoriteRemoved: 'Retiré des favoris.',
  toastNothingExport: 'Rien à exporter. Générez d’abord un kit.',
  toastDownloaded: 'Fichier téléchargé : {filename}',
  toastSettingsSaved: 'Paramètres IA enregistrés.',
  errorInvalidKey: 'Clé API invalide. Vérifiez et réessayez.',
  errorRateLimit: 'Limite de requêtes dépassée. Attendez et réessayez.',
  errorEmptyResponse: 'Réponse vide de l’API.',
  errorApiKeyRequired: 'Clé API requise. Enregistrez-la d’abord.',
  mdSubtitle: 'Promo kit indie',
  mdGeneratedBy: 'Généré par AI Indie Promo Kit',
  mdGenSettings: 'Paramètres de génération',
  mdSetting: 'Paramètre',
  mdValue: 'Valeur',
  mdUiLanguage: 'Langue de l’interface',
  mdGameOverview: 'Aperçu du jeu',
  mdField: 'Champ',
  mdTitle: 'Titre',
  mdGenre: 'Genre',
  mdVisualStyle: 'Style visuel',
  mdCoreMechanic: 'Mécanique principale',
  mdArtEnglish: 'Art — Midjourney (anglais)',
  mdBannerPrompt: 'Prompt bannière',
  mdMenuPrompt: 'Prompt menu',
  mdMusicEnglish: 'Musique — Suno (anglais)',
  mdStyleTags: 'Tags de style',
  mdLyrics: 'Paroles',
  mdMarketing: 'Marketing',
  mdSteamDesc: 'Description Steam',
  mdTwitterPost: 'Publication Twitter / X',
  mdEnd: 'Fin du promo kit',
  apiMarketingNote:
    'Les champs steam_desc et twitter_post doivent être en {language}.',
};

function merge(base, partial) {
  return { ...base, ...partial };
}

const dictionaries = {
  en,
  ru: merge(en, ru),
  uk: merge(en, uk),
  es: merge(en, es),
  de: merge(en, de),
  fr: merge(en, fr),
};

let currentLang = getStoredLanguage();

const listeners = new Set();

export function isSupportedLanguage(lang) {
  return LANGUAGES.some((l) => l.code === lang);
}

export function getLanguage() {
  return currentLang;
}

export function getLocale(lang = currentLang) {
  return LANGUAGES.find((l) => l.code === lang)?.locale || 'en-US';
}

export function getLanguageDisplayName(lang) {
  return LANGUAGES.find((l) => l.code === lang)?.label || lang;
}

export function getMarketingLanguageName(lang) {
  return MARKETING_LANG_NAMES[lang] || MARKETING_LANG_NAMES.en;
}

function resolveDict(lang) {
  const code = isSupportedLanguage(lang) ? lang : 'en';
  return dictionaries[code] || dictionaries.en;
}

export function t(key, params = {}, lang = currentLang) {
  const dict = resolveDict(lang);
  let str = dict[key] ?? dictionaries.en[key] ?? key;
  Object.entries(params).forEach(([k, v]) => {
    str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
  });
  return str;
}

export function setLanguage(lang) {
  const next = isSupportedLanguage(lang) ? lang : 'ru';
  if (next === currentLang) {
    applyTranslations();
    return;
  }
  currentLang = next;
  setStoredLanguage(next);
  document.documentElement.lang = next;
  applyTranslations();
  notifyListeners();
}

export function onLanguageChange(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function notifyListeners() {
  listeners.forEach((fn) => fn(currentLang));
}

export function populateLanguageSelect() {
  const select = document.getElementById('lang-select');
  if (!select) return;
  select.innerHTML = LANGUAGES.map(
    (l) => `<option value="${l.code}">${l.label}</option>`
  ).join('');
  select.value = currentLang;
}

export function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (!key) return;
    el.textContent = t(key);
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (key) el.placeholder = t(key);
  });

  document.querySelectorAll('[data-i18n-title]').forEach((el) => {
    const key = el.getAttribute('data-i18n-title');
    if (key) el.title = t(key);
  });

  document.querySelectorAll('[data-i18n-aria]').forEach((el) => {
    const key = el.getAttribute('data-i18n-aria');
    if (key) el.setAttribute('aria-label', t(key));
  });

  const titleEl = document.querySelector('title[data-i18n]');
  if (titleEl) titleEl.textContent = t('appTitle');

  const langSelect = document.getElementById('lang-select');
  if (langSelect) langSelect.value = currentLang;
}

export function initI18n() {
  currentLang = getStoredLanguage();
  if (!isSupportedLanguage(currentLang)) currentLang = 'ru';
  document.documentElement.lang = currentLang;
  populateLanguageSelect();
  applyTranslations();
}
